version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "11:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: sass
    versions:
    - 1.32.5
